name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Code/Synnotech.AspNetCore.MinimalApis.sln
    - name: Build
      run: dotnet build ./Code/Synnotech.AspNetCore.MinimalApis.sln -c Release --no-restore
    - name: Test
      run: dotnet test ./Code/Synnotech.AspNetCore.MinimalApis.Tests/Synnotech.AspNetCore.MinimalApis.Tests.csproj -c Release --no-build --verbosity normal
